# Generated by Django 5.1.3 on 2024-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('weight_kg', models.FloatField()),
                ('height_m', models.FloatField()),
                ('max_bpm', models.IntegerField()),
                ('avg_bpm', models.IntegerField()),
                ('resting_bpm', models.IntegerField()),
                ('session_duration_hours', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('workout_type', models.CharField(max_length=50)),
                ('fat_percentage', models.FloatField()),
                ('water_intake_liters', models.FloatField()),
                ('workout_frequency', models.IntegerField()),
                ('experience_level', models.IntegerField()),
                ('bmi', models.FloatField()),
            ],
        ),
    ]
