# Generated by Django 5.1.3 on 2024-12-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
